//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laser.Orchard.Mobile.SmsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DriverId {
            get {
                return this.DriverIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverIdField, value) != true)) {
                    this.DriverIdField = value;
                    this.RaisePropertyChanged("DriverId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sms", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sms : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laser.Orchard.Mobile.SmsServiceReference.ArrayOfLong SmsNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        private int SmsValidityPeriodField;
        
        private int SmsProrityField;
        
        private int SmsTipoCodificaField;
        
        private bool MamHaveAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsFromField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Laser.Orchard.Mobile.SmsServiceReference.ArrayOfLong SmsNumber {
            get {
                return this.SmsNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsNumberField, value) != true)) {
                    this.SmsNumberField = value;
                    this.RaisePropertyChanged("SmsNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SmsBody {
            get {
                return this.SmsBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsBodyField, value) != true)) {
                    this.SmsBodyField = value;
                    this.RaisePropertyChanged("SmsBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DriverId {
            get {
                return this.DriverIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverIdField, value) != true)) {
                    this.DriverIdField = value;
                    this.RaisePropertyChanged("DriverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SmsValidityPeriod {
            get {
                return this.SmsValidityPeriodField;
            }
            set {
                if ((this.SmsValidityPeriodField.Equals(value) != true)) {
                    this.SmsValidityPeriodField = value;
                    this.RaisePropertyChanged("SmsValidityPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int SmsPrority {
            get {
                return this.SmsProrityField;
            }
            set {
                if ((this.SmsProrityField.Equals(value) != true)) {
                    this.SmsProrityField = value;
                    this.RaisePropertyChanged("SmsPrority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SmsTipoCodifica {
            get {
                return this.SmsTipoCodificaField;
            }
            set {
                if ((this.SmsTipoCodificaField.Equals(value) != true)) {
                    this.SmsTipoCodificaField = value;
                    this.RaisePropertyChanged("SmsTipoCodifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool MamHaveAlias {
            get {
                return this.MamHaveAliasField;
            }
            set {
                if ((this.MamHaveAliasField.Equals(value) != true)) {
                    this.MamHaveAliasField = value;
                    this.RaisePropertyChanged("MamHaveAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SmsFrom {
            get {
                return this.SmsFromField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsFromField, value) != true)) {
                    this.SmsFromField = value;
                    this.RaisePropertyChanged("SmsFrom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaceHolderMessaggio", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PlaceHolderMessaggio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laser.Orchard.Mobile.SmsServiceReference.PHChiaveValore[] ListaPHChiaveValoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Laser.Orchard.Mobile.SmsServiceReference.PHChiaveValore[] ListaPHChiaveValore {
            get {
                return this.ListaPHChiaveValoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPHChiaveValoreField, value) != true)) {
                    this.ListaPHChiaveValoreField = value;
                    this.RaisePropertyChanged("ListaPHChiaveValore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PHChiaveValore", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PHChiaveValore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChiaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Chiave {
            get {
                return this.ChiaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ChiaveField, value) != true)) {
                    this.ChiaveField = value;
                    this.RaisePropertyChanged("Chiave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valore {
            get {
                return this.ValoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoreField, value) != true)) {
                    this.ValoreField = value;
                    this.RaisePropertyChanged("Valore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Config", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Config : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Laser.Orchard.Mobile.SmsServiceReference.enumProtocollo ProtocolloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MultialiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laser.Orchard.Mobile.SmsServiceReference.ArrayOfString ListaAliasField;
        
        private int MaxLenghtSmsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Laser.Orchard.Mobile.SmsServiceReference.enumProtocollo Protocollo {
            get {
                return this.ProtocolloField;
            }
            set {
                if ((this.ProtocolloField.Equals(value) != true)) {
                    this.ProtocolloField = value;
                    this.RaisePropertyChanged("Protocollo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Multialias {
            get {
                return this.MultialiasField;
            }
            set {
                if ((object.ReferenceEquals(this.MultialiasField, value) != true)) {
                    this.MultialiasField = value;
                    this.RaisePropertyChanged("Multialias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Laser.Orchard.Mobile.SmsServiceReference.ArrayOfString ListaAlias {
            get {
                return this.ListaAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaAliasField, value) != true)) {
                    this.ListaAliasField = value;
                    this.RaisePropertyChanged("ListaAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MaxLenghtSms {
            get {
                return this.MaxLenghtSmsField;
            }
            set {
                if ((this.MaxLenghtSmsField.Equals(value) != true)) {
                    this.MaxLenghtSmsField = value;
                    this.RaisePropertyChanged("MaxLenghtSms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enumProtocollo", Namespace="http://tempuri.org/")]
    public enum enumProtocollo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAM = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMPP = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusByExtId", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StatusByExtId : Laser.Orchard.Mobile.SmsServiceReference.SmsStatus {
        
        private long SmsNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long SmsNumber {
            get {
                return this.SmsNumberField;
            }
            set {
                if ((this.SmsNumberField.Equals(value) != true)) {
                    this.SmsNumberField = value;
                    this.RaisePropertyChanged("SmsNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsStatus", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Laser.Orchard.Mobile.SmsServiceReference.StatusByExtId))]
    public partial class SmsStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsSentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsLastUpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SmsState {
            get {
                return this.SmsStateField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsStateField, value) != true)) {
                    this.SmsStateField = value;
                    this.RaisePropertyChanged("SmsState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SmsSentDate {
            get {
                return this.SmsSentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsSentDateField, value) != true)) {
                    this.SmsSentDateField = value;
                    this.RaisePropertyChanged("SmsSentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SmsLastUpdate {
            get {
                return this.SmsLastUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsLastUpdateField, value) != true)) {
                    this.SmsLastUpdateField = value;
                    this.RaisePropertyChanged("SmsLastUpdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceReference.SmsWebServiceSoap")]
    public interface SmsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse SendSMS(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse> SendSMSAsync(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfig", ReplyAction="*")]
        Laser.Orchard.Mobile.SmsServiceReference.GetConfigResponse GetConfig(Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfig", ReplyAction="*")]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetConfigResponse> GetConfigAsync(Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsStateByExternalId", ReplyAction="*")]
        Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse GetSmsStateByExternalId(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsStateByExternalId", ReplyAction="*")]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse> GetSmsStateByExternalIdAsync(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        Laser.Orchard.Mobile.SmsServiceReference.GetStatusResponse GetStatus(Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetStatusResponse> GetStatusAsync(Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.Login login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Laser.Orchard.Mobile.SmsServiceReference.Sms sms;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Laser.Orchard.Mobile.SmsServiceReference.PlaceHolderMessaggio[] listaPH;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(Laser.Orchard.Mobile.SmsServiceReference.Login login, Laser.Orchard.Mobile.SmsServiceReference.Sms sms, Laser.Orchard.Mobile.SmsServiceReference.PlaceHolderMessaggio[] listaPH) {
            this.login = login;
            this.sms = sms;
            this.listaPH = listaPH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfig", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequestBody Body;
        
        public GetConfigRequest() {
        }
        
        public GetConfigRequest(Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConfigRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.Login login;
        
        public GetConfigRequestBody() {
        }
        
        public GetConfigRequestBody(Laser.Orchard.Mobile.SmsServiceReference.Login login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfigResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetConfigResponseBody Body;
        
        public GetConfigResponse() {
        }
        
        public GetConfigResponse(Laser.Orchard.Mobile.SmsServiceReference.GetConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConfigResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.Config GetConfigResult;
        
        public GetConfigResponseBody() {
        }
        
        public GetConfigResponseBody(Laser.Orchard.Mobile.SmsServiceReference.Config GetConfigResult) {
            this.GetConfigResult = GetConfigResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsStateByExternalIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsStateByExternalId", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequestBody Body;
        
        public GetSmsStateByExternalIdRequest() {
        }
        
        public GetSmsStateByExternalIdRequest(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStateByExternalIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.Login login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string externalId;
        
        public GetSmsStateByExternalIdRequestBody() {
        }
        
        public GetSmsStateByExternalIdRequestBody(Laser.Orchard.Mobile.SmsServiceReference.Login login, string externalId) {
            this.login = login;
            this.externalId = externalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsStateByExternalIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsStateByExternalIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponseBody Body;
        
        public GetSmsStateByExternalIdResponse() {
        }
        
        public GetSmsStateByExternalIdResponse(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStateByExternalIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.StatusByExtId[] GetSmsStateByExternalIdResult;
        
        public GetSmsStateByExternalIdResponseBody() {
        }
        
        public GetSmsStateByExternalIdResponseBody(Laser.Orchard.Mobile.SmsServiceReference.StatusByExtId[] GetSmsStateByExternalIdResult) {
            this.GetSmsStateByExternalIdResult = GetSmsStateByExternalIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.Login login;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(Laser.Orchard.Mobile.SmsServiceReference.Login login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(Laser.Orchard.Mobile.SmsServiceReference.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(int GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsWebServiceSoapChannel : Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsWebServiceSoapClient : System.ServiceModel.ClientBase<Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap>, Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap {
        
        public SmsWebServiceSoapClient() {
        }
        
        public SmsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap.SendSMS(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(Laser.Orchard.Mobile.SmsServiceReference.Login login, Laser.Orchard.Mobile.SmsServiceReference.Sms sms, Laser.Orchard.Mobile.SmsServiceReference.PlaceHolderMessaggio[] listaPH) {
            Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequestBody();
            inValue.Body.login = login;
            inValue.Body.sms = sms;
            inValue.Body.listaPH = listaPH;
            Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse retVal = ((Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse> Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap.SendSMSAsync(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse> SendSMSAsync(Laser.Orchard.Mobile.SmsServiceReference.Login login, Laser.Orchard.Mobile.SmsServiceReference.Sms sms, Laser.Orchard.Mobile.SmsServiceReference.PlaceHolderMessaggio[] listaPH) {
            Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequestBody();
            inValue.Body.login = login;
            inValue.Body.sms = sms;
            inValue.Body.listaPH = listaPH;
            return ((Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laser.Orchard.Mobile.SmsServiceReference.GetConfigResponse Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap.GetConfig(Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequest request) {
            return base.Channel.GetConfig(request);
        }
        
        public Laser.Orchard.Mobile.SmsServiceReference.Config GetConfig(Laser.Orchard.Mobile.SmsServiceReference.Login login) {
            Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequestBody();
            inValue.Body.login = login;
            Laser.Orchard.Mobile.SmsServiceReference.GetConfigResponse retVal = ((Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap)(this)).GetConfig(inValue);
            return retVal.Body.GetConfigResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetConfigResponse> Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap.GetConfigAsync(Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequest request) {
            return base.Channel.GetConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetConfigResponse> GetConfigAsync(Laser.Orchard.Mobile.SmsServiceReference.Login login) {
            Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetConfigRequestBody();
            inValue.Body.login = login;
            return ((Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap)(this)).GetConfigAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap.GetSmsStateByExternalId(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest request) {
            return base.Channel.GetSmsStateByExternalId(request);
        }
        
        public Laser.Orchard.Mobile.SmsServiceReference.StatusByExtId[] GetSmsStateByExternalId(Laser.Orchard.Mobile.SmsServiceReference.Login login, string externalId) {
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequestBody();
            inValue.Body.login = login;
            inValue.Body.externalId = externalId;
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse retVal = ((Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap)(this)).GetSmsStateByExternalId(inValue);
            return retVal.Body.GetSmsStateByExternalIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse> Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap.GetSmsStateByExternalIdAsync(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest request) {
            return base.Channel.GetSmsStateByExternalIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse> GetSmsStateByExternalIdAsync(Laser.Orchard.Mobile.SmsServiceReference.Login login, string externalId) {
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequestBody();
            inValue.Body.login = login;
            inValue.Body.externalId = externalId;
            return ((Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap)(this)).GetSmsStateByExternalIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laser.Orchard.Mobile.SmsServiceReference.GetStatusResponse Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap.GetStatus(Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public int GetStatus(Laser.Orchard.Mobile.SmsServiceReference.Login login) {
            Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequestBody();
            inValue.Body.login = login;
            Laser.Orchard.Mobile.SmsServiceReference.GetStatusResponse retVal = ((Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetStatusResponse> Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap.GetStatusAsync(Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetStatusResponse> GetStatusAsync(Laser.Orchard.Mobile.SmsServiceReference.Login login) {
            Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetStatusRequestBody();
            inValue.Body.login = login;
            return ((Laser.Orchard.Mobile.SmsServiceReference.SmsWebServiceSoap)(this)).GetStatusAsync(inValue);
        }
    }
}
