using Orchard;

namespace Laser.Orchard.StartupConfig.Services {
    public interface IThemeHelperService : IDependency {
        /// <summary>
        /// The urlPrefix for the tenant. Saves us from having to recompute it in each shape 
        /// we need it in.
        /// </summary>
        string UrlPrefix { get; }

        /// <summary>
        /// Formats the URL correctly, accounting for tenant prefixes and such.
        /// The urls generated by this method are correct as relative urls to the
        /// application (i.e. they work as internal links within the application)
        /// </summary>
        /// <param name="path">The URL that requires formatting. This should be 
        /// an URL related to the tenant's base url, except "~/"</param>
        /// <returns></returns>
        string ProperUrl(string path);

        /// <summary>
        /// returns the url for the Home page in the current culture
        /// </summary>
        /// <returns></returns>
        string GetLocalizedHomeUrl();
    }
}
