//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Laser.Orchard.BikeSharing.com.mobilityparc.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StationOpWSServiceSoapBinding", Namespace="http://www.mobility-parc.com/ws")]
    public partial class StationOpWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback retrieveBicyclesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StationOpWSService() {
            this.Url = global::Laser.Orchard.BikeSharing.Properties.Settings.Default.Laser_Orchard_BikeSharing_com_mobilityparc_www_StationOpWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event retrieveBicyclesCompletedEventHandler retrieveBicyclesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.mobility-parc.com/ws", ResponseNamespace="http://www.mobility-parc.com/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetrieveBikesWSResp")]
        public RetrieveBikesWSResp retrieveBicycles(string stationName) {
            object[] results = this.Invoke("retrieveBicycles", new object[] {
                        stationName});
            return ((RetrieveBikesWSResp)(results[0]));
        }
        
        /// <remarks/>
        public void retrieveBicyclesAsync(string stationName) {
            this.retrieveBicyclesAsync(stationName, null);
        }
        
        /// <remarks/>
        public void retrieveBicyclesAsync(string stationName, object userState) {
            if ((this.retrieveBicyclesOperationCompleted == null)) {
                this.retrieveBicyclesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveBicyclesOperationCompleted);
            }
            this.InvokeAsync("retrieveBicycles", new object[] {
                        stationName}, this.retrieveBicyclesOperationCompleted, userState);
        }
        
        private void OnretrieveBicyclesOperationCompleted(object arg) {
            if ((this.retrieveBicyclesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveBicyclesCompleted(this, new retrieveBicyclesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobility-parc.com/ws")]
    public partial class RetrieveBikesWSResp {
        
        private int errorField;
        
        private BikeWSResp[] bikeWSRespsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bikeWSResps", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BikeWSResp[] bikeWSResps {
            get {
                return this.bikeWSRespsField;
            }
            set {
                this.bikeWSRespsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobility-parc.com/ws")]
    public partial class BikeWSResp {
        
        private string bikeUidField;
        
        private string bikeNameField;
        
        private int batteryLevelField;
        
        private int terminalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bikeUid {
            get {
                return this.bikeUidField;
            }
            set {
                this.bikeUidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bikeName {
            get {
                return this.bikeNameField;
            }
            set {
                this.bikeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int batteryLevel {
            get {
                return this.batteryLevelField;
            }
            set {
                this.batteryLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void retrieveBicyclesCompletedEventHandler(object sender, retrieveBicyclesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveBicyclesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveBicyclesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetrieveBikesWSResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetrieveBikesWSResp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591